"""Initial migration

Revision ID: 0a0336a337b3
Revises: 
Create Date: 2026-06-25 02:24:48.367456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a0336a337b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('current_status', sa.String(length=50), nullable=False),
    sa.Column('target_status', sa.String(length=50), nullable=False),
    sa.Column('is_managed', sa.Boolean(), nullable=False),
    sa.Column('budget_limit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('spend_today', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_days_left', sa.Integer(), nullable=True),
    sa.Column('stock_days_min', sa.Integer(), nullable=True),
    sa.Column('schedule_enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaigns')
    # ### end Alembic commands ###
