"""fix_typo_in_logs

Revision ID: 553f5e31ed89
Revises: a33e747f693d
Create Date: 2026-06-25 04:00:36.515371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '553f5e31ed89'
down_revision: Union[str, Sequence[str], None] = 'a33e747f693d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation_logs', sa.Column('previous_target', sa.String(length=50), nullable=False))
    op.drop_column('evaluation_logs', 'previous_targer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation_logs', sa.Column('previous_targer', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('evaluation_logs', 'previous_target')
    # ### end Alembic commands ###
